[workspace]
members = [ "crates/cmds",
    "crates/common",
    "crates/db",
    "crates/quick-kv",
    "crates/server"
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.37.0", features = ["full"] }
bytes = "1.6.0"
tracing = "0.1.40"