[package]
name = "quick-kv"
description = "A Fast Key-Value File Database"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/ThatGuyJamal/quick-kv"
documentation = "https://docs.rs/quick-kv"
publish = true

authors = ["ThatGuyJamal <thatguyjamalbiz@gmai.com>"]
exclude = ["examples/*", ".gitignore", ".github/"]
readme = "README.md"

categories = ["database", "caching"]
license = "MIT"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.188", features = ["derive"] }

[dev-dependencies]
tempfile = "3.8.0"
