[package]
name = "quick-kv"
description = "A fast and minimal key-value database."
version = "0.2.0"
edition = "2021"
repository = "https://github.com/ThatGuyJamal/quick-kv"
documentation = "https://docs.rs/quick-kv"
publish = true
resolver = "2"

authors = ["ThatGuyJamal <thatguyjamalbiz@gmai.com>"]
exclude = ["examples/*", ".gitignore", ".github/", ".idea/", ".vscode/", "scripts/"]
readme = "README.md"

categories = ["database", "caching"]
license = "MIT"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.188", features = ["derive"] }

# Deps for the full feature
rayon = { version = "1.8.0", optional = true }
simple_logger = { version = "4.2.0", optional = true, features = ["threads", "colored"] }
time = { version = "^0.3.29", features = [], optional = true }
log = { version = "0.4.20", optional = true }

[dev-dependencies]
tempfile = "3.8.0"

[features]
default = []
full = ["rayon", "simple_logger", "time", "log"]

[[example]]
name = "basic"

[[example]]
name = "advanced"
required-features = ["full"]
